# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3LOgp2k69o0mN_mOy2MvXXm7ha1VgTu
"""

!pip install -q openai
!pip install openai==0.28

import openai

openai.api_key = 'sk-proj-o2gbxkSlp29TVVB47FsRT3BlbkFJgGR5gNmoUDxkcqUAu5e1'

messages = [
    {"role": "system", "content": "You are a kind helpful assistant that help answer questions concerning transforming residential homes into sustainable homes  ."},
]

while True:
    message = input("User : ")
    if message:
        messages.append(
            {"role": "user", "content": message},
        )
        chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=messages,
            temperature=0.7, max_tokens=100

        )

    reply = chat.choices[0].message.content
    print(f"ChatGPT: {reply}")
    messages.append({"role": "assistant", "content": reply})
